# Site settings
author: Laura Darlak
title: Me, Myself, and Ruby
header-img: img/home-bg.png
email: laura@polyporedesign.com
copyright_name: Laura Darlak
description: > # this means to ignore newlines until "baseurl:"
  Finding Myself in the Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lauradarlak

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
